In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [23]:
with open('../list_of_sentences', 'r+') as f:
    documents = f.readlines()

In [29]:
for i in range(len(documents)):
    documents[i] = documents[i][:-1]

In [30]:
documents

['good morning',
 'how are you doing ?',
 'the weather is awesome today',
 'samsung',
 'good afternoon',
 'baseball is played in the USA',
 'there is a thunderstorm ',
 'are you doing good ?',
 'The polar regions are melting"',
 'apple',
 'nokia',
 'cricket is a fun game',
 'the climate change is a problem']

In [34]:
len(documents)

13

In [32]:
tf_idf = TfidfVectorizer()
tf_idf_matrix = tf_idf.fit_transform(documents)

In [33]:
tf_idf_matrix.shape

(13, 30)

In [46]:
sim1 = cosine_similarity(tf_idf_matrix[0:1], tf_idf_matrix[1:])

In [47]:
sim1

array([[0.        , 0.        , 0.        , 0.36899732, 0.        ,
        0.        , 0.2849837 , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [50]:
np.argmax(sim1)

3

In [66]:
np.argwhere(np.logical_and(sim1>0, sim1<1))

array([[0, 3],
       [0, 6]])

In [63]:
def find_similar(documents, document_matrix):
    similar_list = []
    for i in range(len(documents)):
        sim = cosine_similarity(document_matrix[i:i+1], document_matrix)[0]
        print(sim)
        print()
        

In [64]:
find_similar(documents, tf_idf_matrix)

[1.         0.         0.         0.         0.36899732 0.
 0.         0.2849837  0.         0.         0.         0.
 0.        ]

[0.         1.         0.         0.         0.         0.
 0.         0.72528433 0.16559202 0.         0.         0.
 0.        ]

[0.         0.         1.         0.         0.         0.20001211
 0.1292429  0.         0.1197898  0.         0.         0.10854054
 0.22438284]

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[0.36899732 0.         0.         0.         1.         0.
 0.         0.2849837  0.         0.         0.         0.
 0.        ]

[0.         0.         0.20001211 0.         0.         1.
 0.11520553 0.         0.10677916 0.         0.         0.0967517
 0.20001211]

[0.         0.         0.1292429  0.         0.         0.11520553
 1.         0.         0.         0.         0.         0.13798683
 0.1292429 ]

[0.2849837  0.72528433 0.         0.         0.2849837  0.
 0.         1.         0.17806187 0.         0.         0.
 0.      